### ISSUE TITLE
bintray binary link is broken (404)

### ISSUE THREAD

**Issue by kstevenard** [blackducksoftware/enterprise-utility-suite#3]
Hi,
Just FYI the bintray link listed in the readme is not working. i will build it on my side, but could be good to provide a binary version of it

**Comment by stavvy-akamen** [comment]
There should be artifacts under releases.   But will look into it.

**Comment by stevebillings** [comment]
Hi Kevin, thanks for the heads up on this; I had neglected to finish the release process on this one. I have just released v1.5.0. I fixed the link in the README, but only after I'd finished the release, but in the latest version of the README that link is now fixed (it directs to the release on github itself).
